-- MySQL Script generated by MySQL Workbench
-- 12/01/15 14:40:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema laboratorio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laboratorio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laboratorio` DEFAULT CHARACTER SET utf8 ;
USE `laboratorio` ;

-- -----------------------------------------------------
-- Table `laboratorio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `funcao` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laboratorio`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`paciente` (
  `idpaciente` INT NOT NULL,
  `codigoPaciente` VARCHAR(45) NULL,
  `nomePaciente` VARCHAR(80) NULL,
  `requisitante` VARCHAR(80) NULL,
  `idade` VARCHAR(3) NULL,
  PRIMARY KEY (`idpaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laboratorio`.`exames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laboratorio`.`exames` (
  `idexames` INT NOT NULL,
  `idpaciene` INT NULL,
  `data` VARCHAR(10) NULL,
  PRIMARY KEY (`idexames`),
  INDEX `paciente_idx` (`idpaciene` ASC),
  CONSTRAINT `paciente`
    FOREIGN KEY (`idpaciene`)
    REFERENCES `laboratorio`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
